### ISSUE TITLE
Can't compile on Windows

### ISSUE THREAD

**Issue by Tri125** [mc-server/MCServer#2124]
Commit to blame: b9efa02c
File to blame: MemorySettingsRepository.h (at least)
Line to blame: 78

     std::unordered_map<AString, std::unordered_multimap<AString, sValue>> m_Map{};

Errors: 
```
1.	error C1001: An internal error has occurred in the compiler. 
File: \mcserver\src\MemorySettingsRepository.h	
line : 78	Project:	MCServer
```

```
2. error D8040: error creating or communicating with child process	
File :\MCServer\src\cl	
Project: MCServer
```

I had to run a small bisect to find the guilty commit.
I don't know why this wasn't even caught. This is kind of annoying since you only have to test your work once and to see that it doesn't compile.

**Comment by bearbin** [comment]
What version of MSVC are you using?

**Comment by Tri125** [comment]
Visual C++ 2013 with Visual Studio 2013.

**Comment by bearbin** [comment]
Since it's a compiler crash not a warning/error, could you make sure that you've updated to the latest version, even minor version?

**Comment by worktycho** [comment]
Because its a compilier error, what CTP and update are you using?

**Comment by Tri125** [comment]
Visual C++ 2013 is the latest version, still looking if they released any recent minor versions.
Can you elaborate on what CTP mean?

**Comment by Seadragon91** [comment]
I compiled on my side with visual studio 2013, too. No errors.

**Comment by worktycho** [comment]
CTP's are minor updates that add additional features.

**Comment by Tri125** [comment]
Alright, I'm making progress.

Microsoft C/C++ Optimizing Compiler is actually crashing on that line.

**Comment by Tri125** [comment]
@Seadragon91 what is your cl.exe version? Just run cl.exe found under 
     Microsoft Visual Studio 12.0\VC\bin

Microsoft C/C++ Optimizing Compiler Version 18.00.30324 for x86

**Comment by Seadragon91** [comment]
I have `C/C++ Optimizing Compiler Version 18.00.31101 for x86`.

**Comment by tigerw** [comment]
I have found that internal errors may be fixed by trying the build again, or alternatively clicking on Project -> Clean all, and then Rebuild all.

Try that?

**Comment by tigerw** [comment]
Seadragon's version appears to be higher; try the notifications panel at the top right of the IDE (little flag icon) to see if there are any updates.

**Comment by Tri125** [comment]
@tigerw  yep, I tried cleaning and rebuilding all.

I'm currently removing VC 2013 and installing Visual Studio Community 2013 which come with update 4 (I think I only had update 3).

It's taking quite some time, but I'll report back.

**Comment by Tri125** [comment]
That was it, thanks for the help.
Sorry @worktycho for pointing the finger in your directly while it was my machine to blame ;)
